services:
  # Backend API Service
  - type: web
    name: cloudnet-monitor-backend
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: POSTGRES_HOST
        fromDatabase:
          name: cloudnet-postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: cloudnet-postgres
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: cloudnet-postgres
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: cloudnet-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: cloudnet-postgres
          property: password
      - key: ALLOWED_ORIGINS
        value: https://cloudnet-monitor-frontend.onrender.com,https://cloudnet-monitor.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: API_RATE_LIMIT
        value: 100
      - key: BCRYPT_ROUNDS
        value: 10
      - key: ENABLE_WEBSOCKETS
        value: true
      - key: ENABLE_FLOW_MONITORING
        value: true
      - key: ENABLE_PACKET_CAPTURE
        value: false
      - key: ENABLE_CLOUD_INTEGRATION
        value: true
      # InfluxDB Cloud Configuration (Optional - app works without InfluxDB)
      # After deployment, update these values in Render Dashboard:
      # 1. Sign up at https://cloud.influxdata.com
      # 2. Create an organization and bucket
      # 3. Generate an API token
      # 4. Update these environment variables in Render Dashboard
      - key: INFLUX_HOST
        value: "" # Example: https://us-west-2-1.aws.cloud2.influxdata.com
      - key: INFLUX_PORT
        value: 443
      - key: INFLUX_TOKEN
        value: "" # Your InfluxDB Cloud API token
      - key: INFLUX_ORG
        value: "" # Your InfluxDB Cloud organization ID
      - key: INFLUX_BUCKET
        value: cloudnet_metrics

  # Frontend Static Site
  - type: static
    name: cloudnet-monitor-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://cloudnet-monitor-backend.onrender.com/api
      - key: REACT_APP_WS_URL
        value: wss://cloudnet-monitor-backend.onrender.com/ws

databases:
  # PostgreSQL Database for metadata and configuration
  - name: cloudnet-postgres
    databaseName: cloudnet_monitor
    user: postgres
    plan: free
